language: go

os:
  - linux
  - osx

go:
  - tip
  - "1.10"
  - 1.9
  - 1.8
  - 1.14
install:
  - go get github.com/issue9/assert
  - go get github.com/issue9/term/colors
  - go get gopkg.in/fsnotify/fsnotify.v1
